#!/bin/bash
set -e

if [ "$1" = "--init" ]; then

  ## Add in the spotify repository
  curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
  echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

  ## Load in the apps that I use for viewing media
  sudo apt-get -y update
  sudo apt-get -y upgrade
  sudo apt-get -y install jq zathura feh vlc ranger spotify-client gnome-tweaks vlc xclip python3-pip


  # Install the gnome extentions
  pip3 install --upgrade gnome-extensions-cli
  gnome-extensions-cli install 545
  gnome-extensions-cli install 19
  gnome-extensions-cli install 1732

  gnome-extensions-app &&

  # Load in catcuppin gnome theme
  mkdir -p ~/.themes
  wget https://github.com/catppuccin/gtk/releases/download/v0.7.1/Catppuccin-Macchiato-Standard-Lavender-Dark.zip -P ~
  unzip ~/Catppuccin-Macchiato-Standard-Lavender-Dark.zip -d ~/.themes 
  rm ~/Catppuccin-Macchiato-Standard-Lavender-Dark.zip

  gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Macchiato-Standard-Lavender-Dark"
  gsettings set org.gnome.shell.extensions.user-theme name  "Catppuccin-Macchiato-Standard-Lavender-Dark" || true

  # Set the gnome Terminal theme
  curl -L https://raw.githubusercontent.com/catppuccin/gnome-terminal/v0.2.0/install.py | python3 -

  # Turn off stacking and set color
  dconf write /org/gnome/shell/extensions/pop-shell/stacking-with-mouse false
  gsettings set org.gnome.Terminal.Legacy.Settings headerbar false
  gsettings set org.gnome.desktop.interface enable-animations false

  # Zathura Theme
  mkdir -p $HOME/.config/zathura
  wget -O $HOME/.config/zathura/catppuccin-macchiato https://raw.githubusercontent.com/catppuccin/zathura/main/src/catppuccin-macchiato
  echo '
    include catppuccin-macchiato
    set recolor                     "true"
    set recolor-reverse-video       "true"
    set recolor-keephue             "true"
    set selection-clipboard clipboard
  ' > $HOME/.config/zathura/zathurarc
  # Make zathura default for all pdf in xmim
  xdg-mime default org.pwmt.zathura-pdf-poppler.desktop application/pdf
  xdg-mime default org.pwmt.zathura-pdf-poppler.desktop application/x-pdf
  
  # Feh Theme
  mkdir -p $HOME/.config/feh
  wget -O $HOME/.config/feh/keys https://gist.githubusercontent.com/yudi-matsuzake/688a6273339cbb2d7a97a53d0d8ab6c7/raw/74193d26f849353eb578d9da30106170cf9927c9/keys
  xdg-mime default feh.desktop image/jpeg
  xdg-mime default feh.desktop image/png
  xdg-mime default feh.desktop image/gif
  xdg-mime default feh.desktop image/bmp
  xdg-mime default feh.desktop image/svg

  # Ranger
  xdg-mime default ranger.desktop inode/directory
  mkdir -p ~/.config/ranger
  echo '# rifle.conf
# By default, use Vim for most files
mime ^text,  label editor = vim -- "$@"
has xdg-open, flag f = xdg-open "$1"' > $HOME/.config/ranger/rifle.conf

# Firefox tiling
# Define the Firefox profile directory for Linux
firefox_profile_path="$HOME/.mozilla/firefox"
# Check if the Firefox profile directory exists
if [[ ! -d "$firefox_profile_path" ]]; then
    echo "Firefox profile directory not found."
    exit 1
fi
# Locate the default profile folder
profile_folder=$(find "$firefox_profile_path" -maxdepth 1 -name '*.default*' | head -n 1)
# Verify if we found a profile folder
if [[ -z "$profile_folder" ]]; then
    echo "No default profile found."
    exit 1
fi
# Create or append the user.js file with the desired configuration
user_js_path="$profile_folder/user.js"
echo 'user_pref("full-screen-api.ignore-widgets", true);' >> "$user_js_path"
echo "Configuration was added to $user_js_path"

# Wallpaper
# Fetch the image from the url using wget and save it into the specific directory
wget -O ~/.wallpaper http://web.archive.org/web/20230326122534if_/https://raw.githubusercontent.com/catppuccin/wallpapers/main/misc/spooky_spill.jpg
# Set it as your wallpaper
gsettings set org.gnome.desktop.background picture-uri-dark file:///home/$USER/.wallpaper
echo "Remember to set full-screen-api.ignore-widgets to True in about:config"
fi

if ! command -v docker &> /dev/null
then
    echo "Docker is not installed. Proceeding with installation."

    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    
    # Update package listings
    sudo apt-get update

    # Download installation script from Docker's official repository
    sudo curl -fsSL https://get.docker.com -o install-docker.sh 

    # Run the installation script
    sudo sh install-docker.sh 

    # Remove the installation script
    sudo rm install-docker.sh

    # Add the current user to the Docker group
    sudo usermod -aG docker $USER

    sudo apt-get install -y nvidia-container-toolkit
    
    echo "Docker installation complete!"
else
    echo "Docker is already installed."
fi

# Delete and make the pipe
rm -rf ~/pipe
mkfifo ~/pipe 
nohup bash -c 'while true; do 
    eval "$(cat ~/pipe)" &> ~/.pipe_logs.txt
done' &

xhost + local:root

docker pull fonzzy1/vim 

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

mkdir -p ~/.local/bin
ln -sf $SCRIPT_DIR/runit ~/.local/bin/runit

echo "Setup complete!"

