---
title: 2024-06-24
author: Alfie Chadwick
date: "Created: 24 June, 2024 | Knit: `r format(Sys.time(), '%d %B, %Y')`"
---

| Time | Events                 |
| ---- | ------------------     |
| 1    |                        |
| 2    |                        |
| 3    |                        |
| 4    |                        |
| 5    |                        |
| 6    |                        |
| 7    |                        |
| 8    |                        |
| 9    |                        |
| 10   |                        |
| 11   |                        |
| 12   |                        |
| 13   |                        |
| 14   |                        |
| 15   |                        |
| 16   |                        |
| 17   |                        |
| 18   |                        |
| 19   |                        |
| 20   |                        |
| 21   |                        |
| 22   |                        |
| 23   |                        |
| 24   |                        |

## Upcoming Events

2024-07-25 - registrations for 2XU Triathlon
2024-07-22 @ 11:00 for 2 hours - registrations for 2XU Triathlon
Every Monday @ 11:00 for 1 hour - Climate Genie Meeting
Every 2 - Test


## To Do

- [ ] Personal
    - [ ] Book in car for service
    - [o] Home Cleaning
        - [ ] Cat Flea
        - [ ] All my washing
        - [ ] Ikea Shelf
        - [ ] Skateboard Rack
    - [ ] Music Stuff
        - [ ] Fix Epiphone
        - [ ] Music in room
    - [ ] Writing
        - [ ] Taylor Series
            - [ ] Initial Value Problem
            - [ ] Boundary Value Problem
            - [ ] Multi Variable IVP
        - [ ] Spotify Podcasts Playlist
        - [ ] Free Throw Arc Analysis
        - [ ] Selection Bias in Basketball
        - [ ] Markets in Sport
        - [ ] Supermarket Location
        - [ ] Note Taker Write Up
        - [ ] Dice
        - [ ] 3-Team Perdition
        - [ ] Friends Vs Guidance
        - [ ] Series Page
        - [ ] Scale Category Plot
        - [ ] Strength Standards + Hybrid Standards
    - [o] Dev Containers
        - [ ] Editor = News Split
        - [ ] Auto Fold Quarto
        - [ ] Go next and go previous diagnostic
        - [ ] Fix pr generation with start term
        - [ ] Generate BibTeX Citations from Rmd Links
        - [ ] Recurring tasks and events
        - [ ] Smarter printing of events
        - [ ] Smarter printing of tasks
        - [ ] Sports Schedule in Todays
    - [.] Training
        - [ ] Put Bottle Holder on Bike
        - [ ] Put Power Meter on Bike
        - [ ] Sort out power meter return
        - [ ] [Gym Periodization Plan](/Gym%20Periodization%20Plan.qmd)
        - [o] Buy Race Tickets
            - [ ] 2XU Triathlon
                - [ ] Elwood
                - [ ] St Kilda
            - [ ] Iron man

- [ ] Hub 
    - [.] Climate Genie
        - [ ] Connect Accounts to New Email
        - [ ] Fix the issues with Solutions
        - [ ] Ethics Application
        - [ ] Scraping From News.com
        - [ ] Minimise Images
        - [ ] Admin Dashboard
        - [ ] Re-Up DB and Server
        - [ ] Threshold Testing for Model
        - [ ] Investigate Language Normalisation
        - [ ] User in Status
    - [o] Monster OAT
        - [ ] Dual Scatter Plot
- [ ] ADM+S
    - [O] ABC News Values
        - [O] [1M Headlines Clustering](https://github.com/KalykeXIII/wiki) 
            - [ ] Noun Normalisation (Named Entity Recognition)
            - [ ] LDA 
        - [ ] [Bert For Categories](/Bert%20For%20Categories.qmd)


