[core]
markdown.file_extensions = ["md", "markdown", "rmd","qmd","wiki"]

[code_action]
# Enable/disable "Table of Contents" code action
toc.enable = true
# Enable/disable "Create missing linked file" code action
create_missing_file.enable = true

[completion]
wiki.style = "file-stem"
